services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: yugen
      POSTGRES_PASSWORD: yugen_dev
      POSTGRES_DB: yugen_shoko_development
    ports:
      - "4012:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/app
    ports:
      - "4001:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://yugen:yugen_dev@db:5432/yugen_shoko_development

volumes:
  pgdata:
